-- ----------------------------
-- Table structure for TB_AJA_APP_VERSION
-- ----------------------------
DROP TABLE IF EXISTS TB_AJA_APP_VERSION;
CREATE TABLE TB_AJA_APP_VERSION (
  PLATFORM char(1) NOT NULL COMMENT 'PLATFORM I(iOS) A(Android)',
  MARKET_TY char(1) NOT NULL COMMENT '마켓유형 A(Apple) P(Playstore)',
  APP_TY char(2) NOT NULL DEFAULT '00' COMMENT '어플리케이션 유형 00(상용) 02(시연용) 03(스테이징) 04(개발용) 10(배송상용) 14(배송기사개발)',
  OS_VER varchar(20) DEFAULT NULL COMMENT 'MIN_OS_VER',
  APP_VER varchar(20) NOT NULL COMMENT 'APP_VER(00.00.0000)',
  UPDATE_TY char(1) DEFAULT 'S' COMMENT '업데이트유형 F(Force) S(Select),N',
  UPDATE_URL varchar(512) DEFAULT NULL COMMENT 'UPDATE_URL',
  MESSAGE varchar(1023) DEFAULT NULL COMMENT 'MESSAGE',
  USE_YN char(1) NOT NULL DEFAULT 'Y' COMMENT 'USE_YN',
  IS_DELETED tinyint(4) NOT NULL DEFAULT '0' COMMENT 'IS_DELETED',
  CREATED_NO int(11) DEFAULT NULL COMMENT 'CREATED_NO',
  CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATED_AT',
  UPDATED_NO int(11) DEFAULT NULL COMMENT 'UPDATED_NO',
  UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UPDATED_AT',
  PRIMARY KEY (PLATFORM,MARKET_TY,APP_TY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='어플리케이션 버전정보';

-- ----------------------------
-- Table structure for TB_USER_INFO
-- ----------------------------
DROP TABLE IF EXISTS TB_AJA_USER_INFO;
CREATE TABLE TB_AJA_USER_INFO (
  UNO int(11) NOT NULL AUTO_INCREMENT COMMENT 'UNO(사용자NO)',
  USER_ID varchar(128) NOT NULL COMMENT '사용자ID',
  USER_ID_MOD_YN char(1) NOT NULL DEFAULT 'N' COMMENT '사용자 ID 변경을 가입 후 1회만 허용되도록 적용',
  SNS_ID varchar(128) DEFAULT NULL COMMENT 'SNS ID',
  PASSWORD varchar(256) DEFAULT NULL COMMENT '비밀번호',
  MBER_SBSCRB_TY char(1) DEFAULT NULL COMMENT '가입유형: K(카카오) F(페이스북) T(트위터) N(네이버)',
  MBER_SBSCRB_CHANNEL char(1) DEFAULT NULL COMMENT '회원가입채널: M(모바일웹) I(iOS) A(Android) W(웹) Q(QR - 미사용)',
  SBSCRB_STATUS_CD char(1) DEFAULT 'S' COMMENT '가입상태: S(Sign-up) B(Block) U(unsubscribe):탈퇴',
  DEVICE_ID varchar(255) DEFAULT NULL COMMENT 'DEVICE_ID',
  NAME varchar(30) DEFAULT NULL COMMENT 'NAME',
  BIRTHDAY char(8) DEFAULT NULL COMMENT 'BIRTHDAY',
  GENDER char(1) DEFAULT 'U' COMMENT 'GENDER',
  EMAIL_CRTFC_CNFIRM_YN char(1) DEFAULT 'Y' COMMENT '전자우편인증확인가부',
  EMAIL varchar(127) DEFAULT NULL COMMENT 'EMAIL',
  MOBLPHON_CRTFC_CNFIRM_YN char(1) DEFAULT 'Y' COMMENT '핸드폰인증확인가부',
  MOBLPHON_INTR_DIAL_CD varchar(5) DEFAULT '00' COMMENT 'international dialling codes',
  MOBLPHON_NO varchar(30) DEFAULT NULL COMMENT '핸드폰 번호',
  PROFILE_PATH varchar(255) DEFAULT NULL COMMENT '프로파일 이미지 파일경로',
  PROFILE_FILENAME varchar(128) DEFAULT NULL COMMENT '프로파일 이미지 파일명',
  PROFILE_IMG_ORG_FILE_NM varchar(128) DEFAULT NULL COMMENT '프로파일 이미지 (원)파일명칭',
  PROFILE_IMG_SIZE_H int(11) DEFAULT '0' COMMENT '프로파일 이미지 사이즈_H',
  PROFILE_IMG_SIZE_V int(11) DEFAULT '0' COMMENT '프로파일 이미지 사이즈_V',
  SUBS_DT datetime DEFAULT NULL COMMENT '가입 일시',
  UNSUBS_DT datetime DEFAULT NULL COMMENT '탈퇴 일시',
  BLOCK_DT datetime DEFAULT NULL COMMENT 'Block 일시',
  AGR_LOCATION_POLICY_YN char(1) DEFAULT 'Y' COMMENT '위치정보 활용 승인 여부',
  AGR_PRIVACY_POLICY_YN char(1) DEFAULT 'Y' COMMENT '개인정보 활용 승인 여부',
  AGR_RECV_PNS_YN char(1) NOT NULL DEFAULT 'Y' COMMENT 'PNS  수신 여부',
  AGR_RECV_EVENT_YN char(1) NOT NULL DEFAULT 'Y' COMMENT '이벤트정보 수신여부',
  USE_YN char(1) NOT NULL DEFAULT 'Y' COMMENT 'USE_YN Y : 정상	N:비정상',
  IS_DELETED tinyint(4) NOT NULL DEFAULT '0' COMMENT 'IS_DELETED 0:정상	1:미사용',
  CREATED_NO int(11) DEFAULT NULL COMMENT 'CREATED_NO',
  CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATED_AT',
  UPDATED_NO int(11) DEFAULT NULL COMMENT 'UPDATED_NO',
  UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UPDATED_AT',
  PRIMARY KEY (UNO),
  UNIQUE KEY UIX_TB_USER_INFO_USER_ID (USER_ID),
  UNIQUE KEY UIX_TB_USER_INFO_EMAIL (EMAIL),
  UNIQUE KEY UIX_TB_USER_INFO_MOBILE_PHONE (MOBLPHON_INTR_DIAL_CD,MOBLPHON_NO),
  KEY FK_TB_TOUR_AGENCY_INFO_TO_TB_USER_INFO (TOUR_AGENCY_CODE),
  CONSTRAINT FK_TB_TOUR_AGENCY_INFO_TO_TB_USER_INFO FOREIGN KEY (TOUR_AGENCY_CODE) REFERENCES TB_TOUR_AGENCY_INFO (TOUR_AGENCY_CODE)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='사용자 정보';

-- ----------------------------
-- Table structure for TB_USER_INFO_HST
-- ----------------------------
DROP TABLE IF EXISTS TB_AJA_USER_INFO_HST;
CREATE TABLE TB_AJA_USER_INFO_HST (
  HST_SEQNO int(11) NOT NULL AUTO_INCREMENT COMMENT 'HST_SEQNO',
  HST_TY char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'I' COMMENT 'I,O,U',
  HST_CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'HST_CREATED_AT',
  HST_CREATED_USER varchar(30) NOT NULL DEFAULT '0' COMMENT 'HST_CREATED_USER',
  UNO int(11) NOT NULL COMMENT 'UNO(사용자NO)',
  USER_ID varchar(128) NOT NULL COMMENT '사용자ID',
  SNS_ID varchar(128) DEFAULT NULL COMMENT 'SNS ID',
  PASSWORD varchar(256) DEFAULT NULL COMMENT '비밀번호',
  MBER_SBSCRB_TY char(1) DEFAULT 'I' COMMENT '가입유형: W(Wechat) I(Its member) T(여행사회원)',
  MBER_SBSCRB_CHANNEL char(1) DEFAULT 'M' COMMENT '회원가입채널: M(모바일웹) I(iOS) A(Android) W(웹) Q(QR - 미사용)',
  SBSCRB_STATUS_CD char(1) DEFAULT 'S' COMMENT '가입상태: S(Sign-up) B(Block) U(unsubscribe)',
  DEVICE_ID varchar(255) DEFAULT NULL COMMENT 'DEVICE_ID',
  NAME varchar(30) DEFAULT NULL COMMENT 'NAME',
  BIRTHDAY char(8) DEFAULT NULL COMMENT 'BIRTHDAY',
  GENDER char(1) DEFAULT 'U' COMMENT 'GENDER',
  EMAIL_CRTFC_CNFIRM_YN char(1) DEFAULT 'Y' COMMENT '전자우편인증확인가부',
  EMAIL varchar(127) DEFAULT NULL COMMENT 'EMAIL',
  MOBLPHON_CRTFC_CNFIRM_YN char(1) DEFAULT 'Y' COMMENT '핸드폰인증확인가부',
  MOBLPHON_INTR_DIAL_CD varchar(5) DEFAULT '00' COMMENT 'international dialling codes',
  MOBLPHON_NO varchar(30) DEFAULT NULL COMMENT '핸드폰 번호',
  PROFILE_PATH varchar(255) DEFAULT NULL COMMENT '프로파일 이미지 파일경로',
  PROFILE_FILENAME varchar(128) DEFAULT NULL COMMENT '프로파일 이미지 파일명',
  PROFILE_IMG_ORG_FILE_NM varchar(128) DEFAULT NULL COMMENT '프로파일 이미지 (원)파일명칭',
  PROFILE_IMG_SIZE_H int(11) DEFAULT '0' COMMENT '프로파일 이미지 사이즈_H',
  PROFILE_IMG_SIZE_V int(11) DEFAULT '0' COMMENT '프로파일 이미지 사이즈_V',
  SUBS_DT datetime DEFAULT NULL COMMENT '가입 일시',
  UNSUBS_DT datetime DEFAULT NULL COMMENT '탈퇴 일시',
  BLOCK_DT datetime DEFAULT NULL COMMENT 'Block 일시',
  AGR_LOCATION_POLICY_YN char(1) DEFAULT 'Y' COMMENT '위치정보 활용 승인 여부',
  AGR_PRIVACY_POLICY_YN char(1) DEFAULT 'Y' COMMENT '개인정보 활용 승인 여부',
  AGR_RECV_PNS_YN char(1) NOT NULL DEFAULT 'Y' COMMENT 'PNS  수신 여부',
  AGR_RECV_EVENT_YN char(1) NOT NULL DEFAULT 'Y' COMMENT '이벤트정보 수신여부',
  USE_YN char(1) NOT NULL DEFAULT 'Y' COMMENT 'USE_YN',
  IS_DELETED tinyint(4) NOT NULL DEFAULT '0' COMMENT 'IS_DELETED',
  CREATED_NO int(11) DEFAULT NULL COMMENT 'CREATED_NO',
  CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATED_AT',
  UPDATED_NO int(11) DEFAULT NULL COMMENT 'UPDATED_NO',
  UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UPDATED_AT',
  PRIMARY KEY (HST_SEQNO)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='사용자 정보_HST';

